### ISSUE TITLE
Need a marker for current user location

### ISSUE THREAD

**Issue by longtongj28** [longtongj28/fitness-game#2]
1. Research a way to ask user for current location
2. Get the latitude and longitude of the user
3. potentially update that location as the user moves?
4. mark the user with an image or circle
5. pulse the marker so that the user can see where they are on the map

If the user rejects the location request, we should ask the user to input a location. Link to other issue later.

Probably will need checking for if user location is enabled or if their device supports it:
[refer to this for more info](https://stackoverflow.com/questions/14862019/check-if-location-setting-has-been-turned-off-in-users-browser)

**Comment by cchiu727** [comment]
Design for the user location marker
![UserMarker](https://user-images.githubusercontent.com/61135705/159149953-a90e0bf7-f931-4038-8d5d-031ec58c7ca5.png)
r

**Comment by longtongj28** [comment]
Done
