### ISSUE TITLE
Make designs for markers

### ISSUE THREAD

**Issue by longtongj28** [longtongj28/fitness-game#6]
designs

**Comment by cchiu727** [comment]
Made sample designs for map markers, will be able to make more or adjust as needed.
![Artboard 8](https://user-images.githubusercontent.com/61135705/155457411-757a3ac7-4e2d-4f6e-af8f-94130c706b88.png)
![Artboard 1](https://user-images.githubusercontent.com/61135705/155457413-3d6c0e19-253a-412e-8381-b32f57af6ac3.png)
![Artboard 5](https://user-images.githubusercontent.com/61135705/155457415-db9fe725-9ae1-4606-893a-bd7d460b8c88.png)
![Artboard 6](https://user-images.githubusercontent.com/61135705/155457416-d8c46771-c747-47f3-8d1e-7a40da884bae.png)
![Artboard 7](https://user-images.githubusercontent.com/61135705/155457417-93122d1a-0528-4a0f-b687-a418c10fe878.png)
